export const restaurantData = [
  {
    id: 1,
    name: "Aditi Sharma",
    location: "Vijay Nagar, Indore",
    cuisine: "Gujarati Dishes",
    description: "Musician turned home chef offering authentic Gujarati food.",
    rating: 5,
    discount: 60,
    image: "/assets/restu.png",
  },
  {
    id: 2,
    name: "Rajeev Kumar",
    location: "Baner, Pune",
    cuisine: "North Indian",
    description: "Traditional Punjabi meals cooked with love.",
    rating: 4,
    discount: 50,
    image: "/assets/restu.png",
  },
  {
    id: 3,
    name: "Neha Verma",
    location: "Andheri West, Mumbai",
    cuisine: "Maharashtrian",
    description: "Delicious home-style Maharashtrian thalis.",
    rating: 4.5,
    discount: 40,
    image: "/assets/restu.png",
  },
  {
    id: 4,
    name: "Sandeep Joshi",
    location: "Banjara Hills, Hyderabad",
    cuisine: "Andhra",
    description: "Spicy and authentic Andhra curries and biryani.",
    rating: 5,
    discount: 55,
    image: "/assets/restu.png",
  },
  {
    id: 5,
    name: "Anjali Mehta",
    location: "Salt Lake, Kolkata",
    cuisine: "Bengali",
    description: "Authentic Bengali sweets and home meals.",
    rating: 4.2,
    discount: 45,
    image: "/assets/restu.png",
  },
  {
    id: 6,
    name: "Mohit Rana",
    location: "Sector 62, Noida",
    cuisine: "Tandoori & Grill",
    description: "Tandoori specialties straight from home.",
    rating: 4.7,
    discount: 30,
    image: "/assets/restu.png",
  },
  {
    id: 7,
    name: "Sneha Patil",
    location: "Kothrud, Pune",
    cuisine: "South Indian",
    description: "Fluffy idlis, crispy dosas & spicy sambhar.",
    rating: 4.3,
    discount: 50,
    image: "/assets/restu.png",
  },
  {
    id: 8,
    name: "Ravi Shankar",
    location: "JP Nagar, Bengaluru",
    cuisine: "Chettinad",
    description: "Home-cooked Chettinad delicacies.",
    rating: 4.8,
    discount: 60,
    image: "/assets/restu.png",
  },
  {
    id: 9,
    name: "Pooja Nair",
    location: "Anna Nagar, Chennai",
    cuisine: "Kerala",
    description: "Seafood and coconut-rich Kerala cuisine.",
    rating: 4.6,
    discount: 35,
    image: "/assets/restu.png",
  },
  {
    id: 10,
    name: "Aman Gupta",
    location: "Civil Lines, Delhi",
    cuisine: "Mughlai",
    description: "Royal Mughlai kebabs and curries.",
    rating: 5,
    discount: 65,
    image: "/assets/restu.png",
  },
  {
    id: 11,
    name: "Deepika Rathi",
    location: "Alkapuri, Vadodara",
    cuisine: "Rajasthani",
    description: "Dal baati churma, gatte ki sabzi & more.",
    rating: 4.1,
    discount: 40,
    image: "/assets/restu.png",
  },
  {
    id: 12,
    name: "Tanmay Bhosale",
    location: "Swargate, Pune",
    cuisine: "Street Food",
    description: "Street-style vada pav and misal pav.",
    rating: 4.4,
    discount: 55,
    image: "/assets/restu.png",
  },
  {
    id: 13,
    name: "Kiran Desai",
    location: "Satellite, Ahmedabad",
    cuisine: "Jain Food",
    description: "Pure Jain cuisine with traditional flavor.",
    rating: 4.9,
    discount: 50,
    image: "/assets/restu.png",
  },
  {
    id: 14,
    name: "Harshita Saxena",
    location: "Gomti Nagar, Lucknow",
    cuisine: "Awadhi",
    description: "Lucknowi biryani, kebabs, and more.",
    rating: 4.6,
    discount: 70,
    image: "/assets/restu.png",
  },
  {
    id: 15,
    name: "Farhan Qureshi",
    location: "Old City, Bhopal",
    cuisine: "Middle Eastern",
    description: "Home-cooked falafel, hummus, and shawarma.",
    rating: 4.3,
    discount: 60,
    image: "/assets/restu.png",
  },
  {
    id: 16,
    name: "Lavanya Reddy",
    location: "Madhapur, Hyderabad",
    cuisine: "Fusion",
    description: "Innovative fusion of Indian and global flavors.",
    rating: 4.7,
    discount: 45,
    image: "/assets/restu.png",
  },
];
